# Site settings
title: Shoshin
email: hanvonke@gmail.com
description: Data Analytics Curation for Social Good
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shoshin.io" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: "https://twitter.com/shoshingroup"
medium_url: "https://medium.com/shoshin-group"

# Build settings
markdown: kramdown
